### ISSUE TITLE
Become verified apple developer

### ISSUE THREAD

**Issue by edwardmlyte** [plumming/chilly#45]
Current installation process of downloading the binary and adding to path doesn't work out of the box for MacOS Catalina. Stricter rules mean that trying to run `chilly` from a fresh download prompts the following error:
```
"chilly" cannot be opened because the developer cannot be verified
```
So one has to control + click -> open the file in finder, approve running it, in order to execute the binary (or mess with security settings to allow all unknown developer apps to be opened).

**Comment by garethjevans** [comment]
Am wondering if the brew tap thing will assist here?

**Comment by edwardmlyte** [comment]
```
Tapped 1 formula (36 files, 27.9KB).
==> Installing chilly from plumming/chilly
==> Downloading https://github.com/plumming/chilly/releases/download/0.0.9/chilly-darwin-amd64.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/278065155/b2bd2d00-cdad-11ea-91af-15865f56f240?X-Amz-Algorithm=AWS
######################################################################## 100.0%
==> Caveats
How to use this binary
==> Summary
🍺  /usr/local/Cellar/chilly/0.0.9: 5 files, 11.3MB, built in 2 seconds
[edward ~]$ chilly
Have you got the chillies.

Usage:
  chilly [command]
...
```
Looks like it worked.
